In [13]:
import numpy as np
import pandas as pd

In [18]:
def convolution(input, kernel):
    input_rows, input_cols = input.shape
    kernel_rows, kernel_cols = kernel.shape
    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1
    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            output[i, j] = np.sum(input[i:i+kernel_rows, j:j+kernel_cols] * kernel)

    return output


In [19]:
print(convolution(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), np.array([[1,1], [1,1]])))

[[12. 16.]
 [24. 28.]]


In [ ]:
def convolution_strided(input, kernel, stride):
    input_rows, input_cols = input.shape
    kernel_rows, kernel_cols = kernel.shape
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            output[i, j] = np.sum(input[i*stride:i*stride+kernel_rows, j*stride:j*stride+kernel_cols] * kernel)
    return output

print(convolution_strided(np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), np.array([[1, 1], [1, 1]]), stride=1))
def convolution_padded(input, kernel, padding):
    input_padded = np.pad(input, ((padding, padding), (padding, padding)), mode='constant')
    return convolution(input_padded, kernel)
print(convolution_padded(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), np.array([[1, 1], [1, 1]]), padding=1))
def convolution_padded_strided(input, kernel, padding, stride):
    input_padded = np.pad(input, ((padding, padding), (padding, padding)), mode='constant')
    return convolution_strided(input_padded, kernel, stride)
print(convolution_padded_strided(np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), np.array([[1, 1], [1, 1]]), padding=1, stride=2))
def convolution_3d(input, kernel):
    input_depth, input_rows, input_cols = input.shape
    kernel_depth, kernel_rows, kernel_cols = kernel.shape
    output_depth = input_depth - kernel_depth + 1
    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1
    output = np.zeros((output_depth, output_rows, output_cols))

    for d in range(output_depth):
        for i in range(output_rows):
            for j in range(output_cols):
                output[d, i, j] = np.sum(input[d:d+kernel_depth, i:i+kernel_rows, j:j+kernel_cols] * kernel)

    return output
print(convolution_3d(np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [6, 5, 4], [3, 2, 1]]]), 
                     np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])))

[[14. 18. 22.]
 [30. 34. 38.]]
[[ 1.  3.  5.  3.]
 [ 5. 12. 16.  9.]
 [11. 24. 28. 15.]
 [ 7. 15. 17.  9.]]
[[ 1.  5.  4.]
 [14. 34. 20.]]
[[[40. 40.]
  [40. 40.]]]
